on:
  push:
    branches:
      - fujian
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://g-bdui4697.coding.net/api/cci/job/5724268/trigger'  
        method: 'POST'  
        username: 'ptcme8jjdesa'  
        password: '2bc027a47cfc886134599c84a4956dd2daeff81c'  
        customHeaders: '{"Content-Type": "application/json"}'  
        data: '{"ref":"fujian","envs":[{"name":"DOCKER_REPO_NAME","value":"digital-avarta","sensitive":0},{"name":"DOCKERFILE_PATH","value":"Dockerfile","sensitive":0},{"name":"DOCKER_IMAGE_NAME","value":"digital-avatar-web-1","sensitive":0},{"name":"DOCKER_BUILD_CONTEXT","value":".","sensitive":0},{"name":"REMOTE_SSH_PORT","value":"22","sensitive":0},{"name":"REMOTE_CRED","value":"7f3bbb68-45a6-4ee3-9b88-d5c705d62a5b","sensitive":0},{"name":"DOCKER_IMAGE_VERSION","value":"latest","sensitive":0},{"name":"REMOTE_HOST","value":"223.4.250.248","sensitive":0},{"name":"REMOTE_USER_NAME","value":"root","sensitive":0}]}'  
